FROM mcr.microsoft.com/dotnet/core/aspnet:7.0 AS base
COPY . /app
WORKDIR /app

FROM node:lts-buster-slim AS node_base
FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
COPY --from=node_base . .

RUN dotnet restore

ENV NODE_ENV=production
RUN npm ci
RUN npm run build
RUN dotnet build -c Release -o /app/build
FROM build AS publish
RUN dotnet public -c Release -i /app/publish

FROM base AS final
EXPOSE 3000
# EXPOSE 5000
WORKDIR /app
COPY --from=publish /app/publish .

ENTRYPOINT ["dotnet", "dnd-buddy.dll"]